export const CDM_FIXTURES = [
  // GROUPE A
  { id: 1, date: '2026-06-11', heure: '21:00', domicile: 'Mexico', flagD: '🇲🇽', exterieur: 'Ecuador', flagE: '🇪🇨', groupe: 'A', stade: 'Azteca, Mexico City' },
  { id: 2, date: '2026-06-15', heure: '18:00', domicile: 'Jamaica', flagD: '🇯🇲', exterieur: 'Venezuela', flagE: '🇻🇪', groupe: 'A', stade: 'SoFi Stadium, Los Angeles' },
  { id: 3, date: '2026-06-19', heure: '21:00', domicile: 'Mexico', flagD: '🇲🇽', exterieur: 'Jamaica', flagE: '🇯🇲', groupe: 'A', stade: 'Azteca, Mexico City' },
  { id: 4, date: '2026-06-19', heure: '18:00', domicile: 'Ecuador', flagD: '🇪🇨', exterieur: 'Venezuela', flagE: '🇻🇪', groupe: 'A', stade: 'Rose Bowl, Los Angeles' },
  { id: 5, date: '2026-06-23', heure: '21:00', domicile: 'Mexico', flagD: '🇲🇽', exterieur: 'Venezuela', flagE: '🇻🇪', groupe: 'A', stade: 'Azteca, Mexico City' },
  { id: 6, date: '2026-06-23', heure: '21:00', domicile: 'Ecuador', flagD: '🇪🇨', exterieur: 'Jamaica', flagE: '🇯🇲', groupe: 'A', stade: 'SoFi Stadium, Los Angeles' },
  // GROUPE B
  { id: 7, date: '2026-06-12', heure: '21:00', domicile: 'USA', flagD: '🇺🇸', exterieur: 'Panama', flagE: '🇵🇦', groupe: 'B', stade: 'MetLife, New York' },
  { id: 8, date: '2026-06-12', heure: '18:00', domicile: 'Bolivia', flagD: '🇧🇴', exterieur: 'New Zealand', flagE: '🇳🇿', groupe: 'B', stade: 'AT&T Stadium, Dallas' },
  { id: 9, date: '2026-06-16', heure: '21:00', domicile: 'USA', flagD: '🇺🇸', exterieur: 'Bolivia', flagE: '🇧🇴', groupe: 'B', stade: 'MetLife, New York' },
  { id: 10, date: '2026-06-16', heure: '18:00', domicile: 'Panama', flagD: '🇵🇦', exterieur: 'New Zealand', flagE: '🇳🇿', groupe: 'B', stade: 'SoFi Stadium, Los Angeles' },
  { id: 11, date: '2026-06-20', heure: '21:00', domicile: 'USA', flagD: '🇺🇸', exterieur: 'New Zealand', flagE: '🇳🇿', groupe: 'B', stade: 'MetLife, New York' },
  { id: 12, date: '2026-06-20', heure: '21:00', domicile: 'Panama', flagD: '🇵🇦', exterieur: 'Bolivia', flagE: '🇧🇴', groupe: 'B', stade: 'AT&T Stadium, Dallas' },
  // GROUPE C
  { id: 13, date: '2026-06-13', heure: '21:00', domicile: 'Canada', flagD: '🇨🇦', exterieur: 'Honduras', flagE: '🇭🇳', groupe: 'C', stade: 'BMO Field, Toronto' },
  { id: 14, date: '2026-06-13', heure: '18:00', domicile: 'Chile', flagD: '🇨🇱', exterieur: 'Australia', flagE: '🇦🇺', groupe: 'C', stade: 'BC Place, Vancouver' },
  { id: 15, date: '2026-06-17', heure: '21:00', domicile: 'Canada', flagD: '🇨🇦', exterieur: 'Chile', flagE: '🇨🇱', groupe: 'C', stade: 'BMO Field, Toronto' },
  { id: 16, date: '2026-06-17', heure: '18:00', domicile: 'Honduras', flagD: '🇭🇳', exterieur: 'Australia', flagE: '🇦🇺', groupe: 'C', stade: 'BC Place, Vancouver' },
  { id: 17, date: '2026-06-21', heure: '21:00', domicile: 'Canada', flagD: '🇨🇦', exterieur: 'Australia', flagE: '🇦🇺', groupe: 'C', stade: 'BMO Field, Toronto' },
  { id: 18, date: '2026-06-21', heure: '21:00', domicile: 'Chile', flagD: '🇨🇱', exterieur: 'Honduras', flagE: '🇭🇳', groupe: 'C', stade: 'BC Place, Vancouver' },
  // GROUPE D
  { id: 19, date: '2026-06-14', heure: '21:00', domicile: 'France', flagD: '🇫🇷', exterieur: 'Morocco', flagE: '🇲🇦', groupe: 'D', stade: 'MetLife, New York' },
  { id: 20, date: '2026-06-14', heure: '18:00', domicile: 'Senegal', flagD: '🇸🇳', exterieur: 'Uzbekistan', flagE: '🇺🇿', groupe: 'D', stade: "Levi's Stadium, San Francisco" },
  { id: 21, date: '2026-06-18', heure: '21:00', domicile: 'France', flagD: '🇫🇷', exterieur: 'Senegal', flagE: '🇸🇳', groupe: 'D', stade: 'MetLife, New York' },
  { id: 22, date: '2026-06-18', heure: '18:00', domicile: 'Morocco', flagD: '🇲🇦', exterieur: 'Uzbekistan', flagE: '🇺🇿', groupe: 'D', stade: 'Hard Rock, Miami' },
  { id: 23, date: '2026-06-22', heure: '21:00', domicile: 'France', flagD: '🇫🇷', exterieur: 'Uzbekistan', flagE: '🇺🇿', groupe: 'D', stade: 'MetLife, New York' },
  { id: 24, date: '2026-06-22', heure: '21:00', domicile: 'Morocco', flagD: '🇲🇦', exterieur: 'Senegal', flagE: '🇸🇳', groupe: 'D', stade: "Levi's Stadium, San Francisco" },
  // GROUPE E
  { id: 25, date: '2026-06-14', heure: '15:00', domicile: 'Germany', flagD: '🇩🇪', exterieur: 'Colombia', flagE: '🇨🇴', groupe: 'E', stade: 'AT&T Stadium, Dallas' },
  { id: 26, date: '2026-06-15', heure: '21:00', domicile: 'Uruguay', flagD: '🇺🇾', exterieur: 'Japan', flagE: '🇯🇵', groupe: 'E', stade: 'Rose Bowl, Los Angeles' },
  { id: 27, date: '2026-06-19', heure: '15:00', domicile: 'Germany', flagD: '🇩🇪', exterieur: 'Uruguay', flagE: '🇺🇾', groupe: 'E', stade: 'AT&T Stadium, Dallas' },
  { id: 28, date: '2026-06-19', heure: '18:00', domicile: 'Colombia', flagD: '🇨🇴', exterieur: 'Japan', flagE: '🇯🇵', groupe: 'E', stade: 'Rose Bowl, Los Angeles' },
  { id: 29, date: '2026-06-23', heure: '21:00', domicile: 'Germany', flagD: '🇩🇪', exterieur: 'Japan', flagE: '🇯🇵', groupe: 'E', stade: 'AT&T Stadium, Dallas' },
  { id: 30, date: '2026-06-23', heure: '21:00', domicile: 'Colombia', flagD: '🇨🇴', exterieur: 'Uruguay', flagE: '🇺🇾', groupe: 'E', stade: 'Hard Rock, Miami' },
  // GROUPE F
  { id: 31, date: '2026-06-15', heure: '15:00', domicile: 'Portugal', flagD: '🇵🇹', exterieur: 'Argentina', flagE: '🇦🇷', groupe: 'F', stade: 'Hard Rock, Miami' },
  { id: 32, date: '2026-06-15', heure: '18:00', domicile: 'South Africa', flagD: '🇿🇦', exterieur: 'South Korea', flagE: '🇰🇷', groupe: 'F', stade: 'SoFi Stadium, Los Angeles' },
  { id: 33, date: '2026-06-19', heure: '21:00', domicile: 'Portugal', flagD: '🇵🇹', exterieur: 'South Africa', flagE: '🇿🇦', groupe: 'F', stade: 'MetLife, New York' },
  { id: 34, date: '2026-06-19', heure: '15:00', domicile: 'Argentina', flagD: '🇦🇷', exterieur: 'South Korea', flagE: '🇰🇷', groupe: 'F', stade: 'Hard Rock, Miami' },
  { id: 35, date: '2026-06-23', heure: '21:00', domicile: 'Portugal', flagD: '🇵🇹', exterieur: 'South Korea', flagE: '🇰🇷', groupe: 'F', stade: 'MetLife, New York' },
  { id: 36, date: '2026-06-23', heure: '21:00', domicile: 'Argentina', flagD: '🇦🇷', exterieur: 'South Africa', flagE: '🇿🇦', groupe: 'F', stade: 'Hard Rock, Miami' },
  // GROUPE G
  { id: 37, date: '2026-06-16', heure: '21:00', domicile: 'Spain', flagD: '🇪🇸', exterieur: 'Brazil', flagE: '🇧🇷', groupe: 'G', stade: 'MetLife, New York' },
  { id: 38, date: '2026-06-16', heure: '15:00', domicile: 'Nigeria', flagD: '🇳🇬', exterieur: 'Saudi Arabia', flagE: '🇸🇦', groupe: 'G', stade: "Levi's Stadium, San Francisco" },
  { id: 39, date: '2026-06-20', heure: '21:00', domicile: 'Spain', flagD: '🇪🇸', exterieur: 'Nigeria', flagE: '🇳🇬', groupe: 'G', stade: 'MetLife, New York' },
  { id: 40, date: '2026-06-20', heure: '18:00', domicile: 'Brazil', flagD: '🇧🇷', exterieur: 'Saudi Arabia', flagE: '🇸🇦', groupe: 'G', stade: 'Rose Bowl, Los Angeles' },
  { id: 41, date: '2026-06-24', heure: '21:00', domicile: 'Spain', flagD: '🇪🇸', exterieur: 'Saudi Arabia', flagE: '🇸🇦', groupe: 'G', stade: 'MetLife, New York' },
  { id: 42, date: '2026-06-24', heure: '21:00', domicile: 'Brazil', flagD: '🇧🇷', exterieur: 'Nigeria', flagE: '🇳🇬', groupe: 'G', stade: "Levi's Stadium, San Francisco" },
  // GROUPE H
  { id: 43, date: '2026-06-16', heure: '18:00', domicile: 'England', flagD: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', exterieur: 'Netherlands', flagE: '🇳🇱', groupe: 'H', stade: 'AT&T Stadium, Dallas' },
  { id: 44, date: '2026-06-17', heure: '15:00', domicile: 'DR Congo', flagD: '🇨🇩', exterieur: 'Qatar', flagE: '🇶🇦', groupe: 'H', stade: 'SoFi Stadium, Los Angeles' },
  { id: 45, date: '2026-06-21', heure: '18:00', domicile: 'England', flagD: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', exterieur: 'DR Congo', flagE: '🇨🇩', groupe: 'H', stade: 'AT&T Stadium, Dallas' },
  { id: 46, date: '2026-06-21', heure: '15:00', domicile: 'Netherlands', flagD: '🇳🇱', exterieur: 'Qatar', flagE: '🇶🇦', groupe: 'H', stade: 'Rose Bowl, Los Angeles' },
  { id: 47, date: '2026-06-25', heure: '21:00', domicile: 'England', flagD: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', exterieur: 'Qatar', flagE: '🇶🇦', groupe: 'H', stade: 'AT&T Stadium, Dallas' },
  { id: 48, date: '2026-06-25', heure: '21:00', domicile: 'Netherlands', flagD: '🇳🇱', exterieur: 'DR Congo', flagE: '🇨🇩', groupe: 'H', stade: 'MetLife, New York' },
  // GROUPE I
  { id: 49, date: '2026-06-17', heure: '21:00', domicile: 'Belgium', flagD: '🇧🇪', exterieur: 'Egypt', flagE: '🇪🇬', groupe: 'I', stade: 'Hard Rock, Miami' },
  { id: 50, date: '2026-06-17', heure: '18:00', domicile: 'Peru', flagD: '🇵🇪', exterieur: 'Costa Rica', flagE: '🇨🇷', groupe: 'I', stade: 'AT&T Stadium, Dallas' },
  { id: 51, date: '2026-06-21', heure: '21:00', domicile: 'Belgium', flagD: '🇧🇪', exterieur: 'Peru', flagE: '🇵🇪', groupe: 'I', stade: 'MetLife, New York' },
  { id: 52, date: '2026-06-21', heure: '18:00', domicile: 'Egypt', flagD: '🇪🇬', exterieur: 'Costa Rica', flagE: '🇨🇷', groupe: 'I', stade: 'Hard Rock, Miami' },
  { id: 53, date: '2026-06-25', heure: '21:00', domicile: 'Belgium', flagD: '🇧🇪', exterieur: 'Costa Rica', flagE: '🇨🇷', groupe: 'I', stade: 'MetLife, New York' },
  { id: 54, date: '2026-06-25', heure: '21:00', domicile: 'Egypt', flagD: '🇪🇬', exterieur: 'Peru', flagE: '🇵🇪', groupe: 'I', stade: 'AT&T Stadium, Dallas' },
  // GROUPE J
  { id: 55, date: '2026-06-18', heure: '21:00', domicile: 'Croatia', flagD: '🇭🇷', exterieur: 'Mexico', flagE: '🇲🇽', groupe: 'J', stade: 'Rose Bowl, Los Angeles' },
  { id: 56, date: '2026-06-18', heure: '15:00', domicile: 'Cameroon', flagD: '🇨🇲', exterieur: 'Iran', flagE: '🇮🇷', groupe: 'J', stade: 'AT&T Stadium, Dallas' },
  { id: 57, date: '2026-06-22', heure: '21:00', domicile: 'Croatia', flagD: '🇭🇷', exterieur: 'Cameroon', flagE: '🇨🇲', groupe: 'J', stade: 'MetLife, New York' },
  { id: 58, date: '2026-06-22', heure: '18:00', domicile: 'Mexico', flagD: '🇲🇽', exterieur: 'Iran', flagE: '🇮🇷', groupe: 'J', stade: 'Azteca, Mexico City' },
  { id: 59, date: '2026-06-26', heure: '21:00', domicile: 'Croatia', flagD: '🇭🇷', exterieur: 'Iran', flagE: '🇮🇷', groupe: 'J', stade: 'Rose Bowl, Los Angeles' },
  { id: 60, date: '2026-06-26', heure: '21:00', domicile: 'Mexico', flagD: '🇲🇽', exterieur: 'Cameroon', flagE: '🇨🇲', groupe: 'J', stade: 'Azteca, Mexico City' },
  // GROUPE K
  { id: 61, date: '2026-06-18', heure: '18:00', domicile: 'Italy', flagD: '🇮🇹', exterieur: 'Tunisia', flagE: '🇹🇳', groupe: 'K', stade: "Levi's Stadium, San Francisco" },
  { id: 62, date: '2026-06-19', heure: '18:00', domicile: 'Cuba', flagD: '🇨🇺', exterieur: 'Indonesia', flagE: '🇮🇩', groupe: 'K', stade: 'SoFi Stadium, Los Angeles' },
  { id: 63, date: '2026-06-22', heure: '15:00', domicile: 'Italy', flagD: '🇮🇹', exterieur: 'Cuba', flagE: '🇨🇺', groupe: 'K', stade: "Levi's Stadium, San Francisco" },
  { id: 64, date: '2026-06-22', heure: '18:00', domicile: 'Tunisia', flagD: '🇹🇳', exterieur: 'Indonesia', flagE: '🇮🇩', groupe: 'K', stade: 'Rose Bowl, Los Angeles' },
  { id: 65, date: '2026-06-26', heure: '21:00', domicile: 'Italy', flagD: '🇮🇹', exterieur: 'Indonesia', flagE: '🇮🇩', groupe: 'K', stade: "Levi's Stadium, San Francisco" },
  { id: 66, date: '2026-06-26', heure: '21:00', domicile: 'Tunisia', flagD: '🇹🇳', exterieur: 'Cuba', flagE: '🇨🇺', groupe: 'K', stade: 'SoFi Stadium, Los Angeles' },
  // GROUPE L
  { id: 67, date: '2026-06-19', heure: '15:00', domicile: 'Switzerland', flagD: '🇨🇭', exterieur: 'Serbia', flagE: '🇷🇸', groupe: 'L', stade: 'Hard Rock, Miami' },
  { id: 68, date: '2026-06-20', heure: '15:00', domicile: 'Algeria', flagD: '🇩🇿', exterieur: 'Paraguay', flagE: '🇵🇾', groupe: 'L', stade: 'MetLife, New York' },
  { id: 69, date: '2026-06-23', heure: '18:00', domicile: 'Switzerland', flagD: '🇨🇭', exterieur: 'Algeria', flagE: '🇩🇿', groupe: 'L', stade: 'Hard Rock, Miami' },
  { id: 70, date: '2026-06-23', heure: '15:00', domicile: 'Serbia', flagD: '🇷🇸', exterieur: 'Paraguay', flagE: '🇵🇾', groupe: 'L', stade: 'AT&T Stadium, Dallas' },
  { id: 71, date: '2026-06-27', heure: '21:00', domicile: 'Switzerland', flagD: '🇨🇭', exterieur: 'Paraguay', flagE: '🇵🇾', groupe: 'L', stade: 'MetLife, New York' },
  { id: 72, date: '2026-06-27', heure: '21:00', domicile: 'Serbia', flagD: '🇷🇸', exterieur: 'Algeria', flagE: '🇩🇿', groupe: 'L', stade: 'Hard Rock, Miami' },
]
